name: autocommit-robot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Set node"
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Run bash"
        run: npm run dev

      - name: "Commit"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: wendZzoo
          author_email: 19844544551@163.com
          message: "chore: update readme by ci"
          add: "*"

        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
